# Generated by Django 3.2.6 on 2021-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
